### ISSUE TITLE
Only run Search + Key Vault (CMK) tests weekly

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#16576]
Based on https://github.com/Azure/azure-sdk-for-net/pull/16484#discussion_r517407677, once weekly tests are realized, we need only test CMK scenarios weekly most likely. The surface area doesn't change much, and it would help reduce costs without sacrificing coverage significantly.

**Comment by heaths** [comment]
In addition, we should change the default back SKU back to "free" and just not allocate a KV. That actually happens now if you call the script like so anyway (handy for re/running non-KV-related tests):
```powershell
New-TestResources.ps1 -ServiceDirectory search -AdditionalParameters @{searchSku='free'}
```

/cc @tg-msft

**Comment by pallavit** [comment]
@heaths is this still a concern. Looking at the ARM template for search I can see us configuring a basic SKU and not a free one but looking at the older issue this was created when weekly tests were being written and we were still looking at efficient ways of clean-up.
/cc: @ShivangiReja

**Comment by heaths** [comment]
It should be possible now, but this work would need to be done. I don't know if weekly tests already pass a parameter that indicates it's weekly, but @benbp could probably suggest some method we can pass as an env var, read in the `TestEnvironment`, and conditionalize both the tests and the ARM template as I do for KV (to provision a single MHSM): https://github.com/Azure/azure-sdk-for-net/blob/80be2eb24a1297b689673673a1bf244f603e5e92/sdk/keyvault/test-resources.json#L156

**Comment by benbp** [comment]
@heaths something like this could work:

```
parameters:
  CloudConfig:
    Public:
      SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources)
      # Do not provision and run HSM tests for nightly pipelines.
      ${{ if not(contains(variables['Build.DefinitionName'])) }}:
        MatrixFilters:
          - ArmTemplateParameters=^(?!.*enableHsm.*true)
```
