### ISSUE TITLE
BlobClient.SyncCopyFromUriAsync fails with "The lease ID specified does not match the lease ID for the blob" when the source URI is from Azure blob storage

### ISSUE THREAD

**Issue by Jawvig** [Azure/azure-sdk-for-net#19094]
**Describe the bug**
Using the Azure.Storage.Blobs client library, when trying to overwrite an existing blob with data that resides in blob storage, using a lease to lock the file, the `Azure.Storage.Blobs.BlobClient.SyncCopyFromUriAsync` operation fails. It receives a 412 error from the REST API and an ErrorCode of `LeaseIdMismatchWithBlobOperation` and the text `The lease ID specified did not match the lease ID for the blob.`

**Expected behavior**
`Azure.Storage.Blobs.BlobClient.SyncCopyFromUriAsync` called with a lease ID will succeed when the source URI is from blob storage itself, and the lease ID is valid.

**Actual behavior (include Exception or Stack Trace)**
It receives the following error in an exception message:
```
       The lease ID specified did not match the lease ID for the blob.
       RequestId:9173351a-501e-00a4-57cf-0df414000000
       Time:2021-02-28T12:45:01.0139914Z
       Status: 412 (The lease ID specified did not match the lease ID for the blob.)
       ErrorCode: LeaseIdMismatchWithBlobOperation

       Headers:
       Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
       x-ms-request-id: 9173351a-501e-00a4-57cf-0df414000000
       x-ms-client-request-id: 0069def0-b853-4389-81b4-b362488634c3
       x-ms-version: 2020-02-10
       x-ms-error-code: LeaseIdMismatchWithBlobOperation
       Date: Sun, 28 Feb 2021 12:45:00 GMT
       Content-Length: 264
       Content-Type: application/xml
```
**To Reproduce**
Below is the full code from `Program.cs` in a .NET 5 console app to reproduce the problem. It has been run on Windows with the following package references:
Azure.Identity: 1.3.0
Azure.Storage.Blobs: 12.8.0

The code is being run from within Visual Studio in which there is an attached account that has membership of the "Owner" and "Storage Blob Data Owner" roles on the destination storage account. The destination storage account has disabled public access, and the destination container is thus private.

The code firstly creates a blob by specifying a source URI which is an image from the public internet.
Then it attempts to overwrite that blob with the same content, but this time specifying a lease that it acquires.
Finally it attempts to overwrite the blob using the same lease but where the source is a blob from a different storage account where the blob has been configured for public access.

The full received error information is in a comment in the code.

Whilst this code doesn't demonstrate it, the same problem occurs when the source URI is a SAS URI to a private blob. 

```csharp
using System;
using Azure.Identity;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using Azure.Storage.Blobs.Specialized;

var publicInternetSourceUri = new Uri(
    "https://purepng.com/public/uploads/large/purepng.com-microsoft-logo-iconlogobrand-logoiconslogos-251519939091wmudn.png");
var publicBlobSourceUri = new Uri("https://intentionallypublicjpg.blob.core.windows.net/pub/ms-windows-logo.png");

const string destinationStorageAccount = "destinationstorageaccount"; // TODO: Change
const string destinationContainerName = "destinationcontainername"; // TODO: Change

// Brand new blob name - doesn't currently exist
var destinationBlobName = $"destination{DateTime.UtcNow.Ticks}.png";
var destinationContainerClient = new BlobContainerClient(
    new Uri($"https://{destinationStorageAccount}.blob.core.windows.net/{destinationContainerName}"),
    new DefaultAzureCredential());
var destinationBlob = destinationContainerClient.GetBlobClient(destinationBlobName);

BlobLeaseClient destinationBlobLease = null;
try
{
    // Setup code - copying something from a public URL to this new blob name:
    await destinationBlob.SyncCopyFromUriAsync(publicInternetSourceUri);

    // Acquire a lease before trying to overwrite the blob.
    destinationBlobLease = destinationBlob.GetBlobLeaseClient();
    await destinationBlobLease.AcquireAsync(
        BlobLeaseClient.InfiniteLeaseDuration,
        new BlobLeaseRequestConditions());

    // Set up the structure for providing the lease ID to the SyncCopyFromUriAsync operations
    var blobOptions = new BlobCopyFromUriOptions
    {
        DestinationConditions = new BlobRequestConditions
        {
            LeaseId = destinationBlobLease.LeaseId
        }
    };

    // Works: Overwriting blob using public internet source data
    await destinationBlob.SyncCopyFromUriAsync(
        publicInternetSourceUri,
        blobOptions);

    // Doesn't work: Overwriting blob using public Azure blob as source daata
    await destinationBlob.SyncCopyFromUriAsync(
        publicBlobSourceUri,
        blobOptions);

    /* It receives the following error in the exception message:

       The lease ID specified did not match the lease ID for the blob.
       RequestId:9173351a-501e-00a4-57cf-0df414000000
       Time:2021-02-28T12:45:01.0139914Z
       Status: 412 (The lease ID specified did not match the lease ID for the blob.)
       ErrorCode: LeaseIdMismatchWithBlobOperation

       Headers:
       Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
       x-ms-request-id: 9173351a-501e-00a4-57cf-0df414000000
       x-ms-client-request-id: 0069def0-b853-4389-81b4-b362488634c3
       x-ms-version: 2020-02-10
       x-ms-error-code: LeaseIdMismatchWithBlobOperation
       Date: Sun, 28 Feb 2021 12:45:00 GMT
       Content-Length: 264
       Content-Type: application/xml
    */
}
catch (Exception ex)
{
    Console.WriteLine(ex.Message);
}
finally
{
    if (destinationBlobLease != null)
        await destinationBlobLease.ReleaseAsync();
}
```
**Environment:**
Windows 10
.NET 5 Console App
Package references:
- Azure.Identity: 1.3.0
- Azure.Storage.Blobs: 12.8.0
Source URI is in Azure blob storage where that blob is either publicly accessible or the URI includes a SAS token
