### ISSUE TITLE
ContainerServiceManagedClusterData Class has no option to enable the Istio add-on

### ISSUE THREAD

**Issue by cwash05** [Azure/azure-sdk-for-net#40953]
### Library name

Azure.ResourceManager.ContainerService

### Please describe the feature.

in Azure.ResourceManager.ContainerService 1.2.0-beta.3 there is no option to enable the Istio add-on.

This should be a property in the ContainerServiceManagedClusterData class

```yaml
  "serviceMeshProfile": {
    "istio": {
      "certificateAuthority": null,
      "components": {
        "egressGateways": null,
        "ingressGateways": null
      },
      "revisions": [
        "asm-1-17"
      ]
    },
    "mode": "Disabled"
  },
  ```
