### ISSUE TITLE
ContainerServiceManagedClusterData Class Has no option to enable Network Observability

### ISSUE THREAD

**Issue by cwash05** [Azure/azure-sdk-for-net#40952]
### Library name

Azure.ResourceManager.ContainerService

### Please describe the feature.

in Azure.ResourceManager.ContainerService 1.2.0-beta.3 there is no option to enable the Network Observability feature. 

this should be an option under the Network Profile section
```yaml
  "networkProfile": {
    "dnsServiceIp": "10.3.0.10",
    "ipFamilies": [
      "IPv4"
    ],
    "kubeProxyConfig": null,
    "loadBalancerProfile": {
      "allocatedOutboundPorts": null,
      "backendPoolType": "nodeIPConfiguration",
      "effectiveOutboundIPs": [
        {
          "id": "/subscriptions/2159f493-f4d2-4f96-ad4d-a9f6ae4ee050/resourceGroups/MC_vader309-EastUS-rg_vader309-aks_eastus/providers/Microsoft.Network/publicIPAddresses/7bfac6b1-17f1-4280-ac1e-73d7b67f6429",
          "resourceGroup": "MC_vader309-EastUS-rg_vader309-aks_eastus"
        }
      ],
      "enableMultipleStandardLoadBalancers": null,
      "idleTimeoutInMinutes": null,
      "managedOutboundIPs": {
        "count": 1,
        "countIpv6": null
      },
      "outboundIPs": null,
      "outboundIpPrefixes": null
    },
    "loadBalancerSku": "Standard",
   *"monitoring"*: {
      "enabled": true
    },
```
